pipeline {
    agent {
        label('docker')
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        buildDiscarder(
            logRotator(
                daysToKeepStr: '7',
                numToKeepStr:'5',
                artifactDaysToKeepStr: '7',
                artifactNumToKeepStr: '5'
            )
        )
    }

    environment {
        CONTAINER = 'harbor.nexenio.local/luca-apps/android:base'
        QUOTE = '\\"'
        C4L_SIGNING_KEY_ALIAS = 'upload'
        COMMIT_HASH = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
    }

    parameters {
        booleanParam(
            name: 'RunTests',
            defaultValue: true,
            description: 'Runs the tests and generates a test report.'
        )
        booleanParam(
            name: 'RunStaticCodeAnalysis',
            defaultValue: true,
            description: 'Runs the static code analysis steps, i.e. linting and Sonarqube.'
        )
        booleanParam(
            name: 'BuildForAllEnvironments',
            defaultValue: false,
            description: 'Builds APKs for all staging environments.'
        )
        booleanParam(
            name: 'UploadToAppCenter',
            defaultValue: false,
            description: 'Build a QS APK and upload it to MS AppCenter for testing.'
        )
        booleanParam(
            name: 'UploadToGooglePlay',
            defaultValue: false,
            description: 'Release the bundle to internal testing track on Google Play Store. This only works on master or release/* branches.'
        )
    }

    stages {
        stage('Docker pull') {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: 'luca-harbor-registry', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD'),
                    string(credentialsId: 'luca-harbor-registry-url', variable: 'DOCKER_REGISTRY')
                ]) {
                    cleanWs()
                    checkout scm
                    sh '''
                       docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD $DOCKER_REGISTRY 
                       docker pull $CONTAINER
                       docker logout
                    '''
                }
            }
        }
        stage('Build Debug') {
            steps {
                sh '''
                    cd Luca
                    docker run --rm -u $(id -u):$(id -g) -v `pwd`:/Luca ${CONTAINER} bash -c "cd /Luca/app; ./../gradlew :app:assembleDebug"
                '''
            }
        }
        stage('Tests') {
            when { anyOf { expression { return params.RunTests } } }
            steps {
                sh '''
                    cd Luca
                    docker run --rm -u $(id -u):$(id -g) -v `pwd`:/Luca ${CONTAINER} bash -c "cd /Luca/app; ./../gradlew :app:testDebug"
                '''
            }
        }
        stage('Static code analysis') {
            when { anyOf { expression { return params.RunStaticCodeAnalysis } } }
            stages {
                stage('Ktlint') {
                    steps {
                        sh '''
                            cd Luca
                            docker run --rm -u $(id -u):$(id -g) -v `pwd`:/Luca ${CONTAINER} bash -c "cd /Luca/app; ./../gradlew :app:ktlintCheck"
                        '''
                    }
                }
                stage('Android lint') {
                    steps {
                        sh '''
                            cd Luca
                            docker run --rm -u $(id -u):$(id -g) -v `pwd`:/Luca ${CONTAINER} bash -c "cd /Luca/app; ./../gradlew :app:lintDebug"
                        '''
                    }
                }
                stage('Sonar') {
                    steps {
                        withSonarQubeEnv('sonarqube-luca') {
                            sh '''
                                cd Luca
                                GENERAL_PARAMS="-PSONAR_HOST_URL=$SONAR_HOST_URL -PSONAR_AUTH_TOKEN=$SONAR_AUTH_TOKEN -PBRANCH_NAME=$BRANCH_NAME"
                                CMD="cd /Luca/app; ./../gradlew :app:sonarqube --stacktrace $GENERAL_PARAMS"
                                docker run --rm -u $(id -u):$(id -g) -v `pwd`:/Luca ${CONTAINER} bash -c "$CMD"
                            '''
                        }
                    }
                }
            }
        }
        stage('Build Dev APK') {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: "luca-staging-api-basic-auth-user-pw", usernameVariable: 'STAGING_API_USERNAME', passwordVariable: 'STAGING_API_PASSWORD'),
                    string(credentialsId: 'luca-android-staging-attestation-token', variable: 'SAFETY_NET_API_KEY'),
                ]) {
                    sh '''
                        cd Luca
                        GENERAL_PARAMS="-PCOMMIT_HASH=$QUOTE$COMMIT_HASH$QUOTE -PSAFETY_NET_API_KEY=$QUOTE$SAFETY_NET_API_KEY$QUOTE"
                        STAGING_PARAMS="-PSTAGING_API_USERNAME=$QUOTE$STAGING_API_USERNAME$QUOTE -PSTAGING_API_PASSWORD=$QUOTE$STAGING_API_PASSWORD$QUOTE"
                        CMD="cd /Luca/app; ./../gradlew :app:assembleDebug $GENERAL_PARAMS $STAGING_PARAMS"
                        docker run --rm -u $(id -u):$(id -g) -v `pwd`:/Luca ${CONTAINER} bash -c "$CMD"
                    '''
                }
            }
        }
        stage('Build Staging APKs') {
            when {
                anyOf {
                    anyOf { branch 'release/*'; branch 'master' }
                    expression { return params.BuildForAllEnvironments }
                }
            }
            steps {
                withCredentials([
                    usernamePassword(credentialsId: "luca-staging-api-basic-auth-user-pw", usernameVariable: 'STAGING_API_USERNAME', passwordVariable: 'STAGING_API_PASSWORD'),
                    string(credentialsId: 'luca-android-staging-attestation-token', variable: 'SAFETY_NET_API_KEY'),
                ]) {
                    sh '''
                        cd Luca
                        GENERAL_PARAMS="-PCOMMIT_HASH=$QUOTE$COMMIT_HASH$QUOTE -PSAFETY_NET_API_KEY=$QUOTE$SAFETY_NET_API_KEY$QUOTE"
                        STAGING_PARAMS="-PSTAGING_API_USERNAME=$QUOTE$STAGING_API_USERNAME$QUOTE -PSTAGING_API_PASSWORD=$QUOTE$STAGING_API_PASSWORD$QUOTE"
                        CMD="cd /Luca/app; ./../gradlew :app:assembleQs :app:assembleAqs :app:assembleHotfix :app:assemblePentest :app:assembleP1 :app:assembleP2 :app:assembleP3 :app:assembleDemo :app:assembleRelease :app:assemblePreprod $GENERAL_PARAMS $STAGING_PARAMS"
                        docker run --rm -u $(id -u):$(id -g) -v `pwd`:/Luca ${CONTAINER} bash -c "$CMD"
                    '''
                }
            }
        }
        stage('Upload to AppCenter') {
            when {
                anyOf {
                    anyOf { branch 'release/*'; branch 'master'; branch 'dev' }
                    expression { return params.UploadToAppCenter }
                }
            }
            steps {
                withCredentials([
                    usernamePassword(credentialsId: "luca-staging-api-basic-auth-user-pw", usernameVariable: 'STAGING_API_USERNAME', passwordVariable: 'STAGING_API_PASSWORD'),
                    string(credentialsId: 'luca-android-appcenter-token', variable: 'APPCENTER_TOKEN'),
                    string(credentialsId: 'luca-android-staging-attestation-token', variable: 'SAFETY_NET_API_KEY'),
                ]) {
                    sh '''#!/bin/bash
                        cd Luca
                        if [[ \"$BUILD_TAG\" == *"master"* ]]; then
                            TASK=":app:assembleRelease"
                            APP_VARIANT=release
                        elif [[ \"$BUILD_TAG\" == *"release"* ]]; then
                            TASK=":app:assemblePreprod"
                            APP_VARIANT=preprod
                        else
                            TASK=":app:assembleP2"
                            APP_VARIANT=p2
                        fi
                        GENERAL_PARAMS="-PCOMMIT_HASH=$QUOTE$COMMIT_HASH$QUOTE -PSAFETY_NET_API_KEY=$QUOTE$SAFETY_NET_API_KEY$QUOTE"
                        STAGING_PARAMS="-PSTAGING_API_USERNAME=$QUOTE$STAGING_API_USERNAME$QUOTE -PSTAGING_API_PASSWORD=$QUOTE$STAGING_API_PASSWORD$QUOTE"
                        CMD="cd /Luca/app; ./../gradlew $TASK $GENERAL_PARAMS $STAGING_PARAMS"
                        docker run --rm -u $(id -u):$(id -g) -v `pwd`:/Luca ${CONTAINER} bash -c "$CMD"
                        cd .. && ./Luca/scripts/rename_output_files && cd Luca
                        CMD="cd /Luca/app; npm install -g appcenter-cli"
                        CMD="$CMD && appcenter distribute release --app culture4life/luca-Android --file build/outputs/apk/$APP_VARIANT/app-$APP_VARIANT_*.apk --group "Testers" --token $APPCENTER_TOKEN"
                        docker run --rm -v `pwd`:/Luca --entrypoint /bin/sh node:14.16.0-alpine3.13 -c "$CMD"
                    '''
                }
            }
        }
        stage('Build Production APK') {
            when { anyOf { branch 'master' } }
            steps {
                withCredentials([
                    file(credentialsId: 'luca-android-keystore', variable: 'KEYSTORE_FILE'),
                    string(credentialsId: 'luca-android-upload-key-pw', variable: 'C4L_SIGNING_KEY_PASSWORD'),
                    string(credentialsId: 'luca-android-keystore-pw', variable: 'C4L_SIGNING_STORE_PASSWORD'),
                    string(credentialsId: 'luca-android-attestation-token', variable: 'SAFETY_NET_API_KEY'),
                ]) {
                    sh '''
                        cd Luca
                        GENERAL_PARAMS="-PCOMMIT_HASH=$QUOTE$COMMIT_HASH$QUOTE -PSAFETY_NET_API_KEY=$QUOTE$SAFETY_NET_API_KEY$QUOTE"
                        LOCAL_KEYSTORE_FILE=$(basename $KEYSTORE_FILE)
                        KEYSTORE_PARAMS="-PC4L_SIGNING_STORE_FILE=$LOCAL_KEYSTORE_FILE -PC4L_SIGNING_KEY_PASSWORD=$C4L_SIGNING_KEY_PASSWORD -PC4L_SIGNING_KEY_ALIAS=$C4L_SIGNING_KEY_ALIAS -PC4L_SIGNING_STORE_PASSWORD=$C4L_SIGNING_STORE_PASSWORD"
                        CMD="cd /Luca/app; ./../gradlew dependencyCheckAnalyze :app:assembleProduction $GENERAL_PARAMS $KEYSTORE_PARAMS"
                        docker run --rm -u $(id -u):$(id -g) -v `pwd`:/Luca -v $KEYSTORE_FILE:/Luca/app/$LOCAL_KEYSTORE_FILE ${CONTAINER} bash -c "$CMD"
                    '''
                }
            }
        }
        stage('Upload to Google Play') {
            when {
                allOf {
                    anyOf { branch 'release/*'; branch 'master' }
                    expression { return params.UploadToGooglePlay }
                }
            }
            steps {
                withCredentials([
                    file(credentialsId: 'luca-android-keystore', variable: 'KEYSTORE_FILE'),
                    file(credentialsId: 'c4l-play-console-service-account-json', variable: 'SERVICE_ACCOUNT_FILE'),
                    string(credentialsId: 'luca-android-upload-key-pw', variable: 'C4L_SIGNING_KEY_PASSWORD'),
                    string(credentialsId: 'luca-android-keystore-pw', variable: 'C4L_SIGNING_STORE_PASSWORD'),
                    string(credentialsId: 'luca-android-attestation-token', variable: 'SAFETY_NET_API_KEY'),
                ]) {
                    sh '''
                        cd Luca
                        GENERAL_PARAMS="-PCOMMIT_HASH=$QUOTE$COMMIT_HASH$QUOTE -PSAFETY_NET_API_KEY=$QUOTE$SAFETY_NET_API_KEY$QUOTE"
                        LOCAL_KEYSTORE_FILE=$(basename $KEYSTORE_FILE)
                        KEYSTORE_PARAMS="-PC4L_SIGNING_STORE_FILE=$LOCAL_KEYSTORE_FILE -PC4L_SIGNING_KEY_PASSWORD=$C4L_SIGNING_KEY_PASSWORD -PC4L_SIGNING_KEY_ALIAS=$C4L_SIGNING_KEY_ALIAS -PC4L_SIGNING_STORE_PASSWORD=$C4L_SIGNING_STORE_PASSWORD"
                        CMD="cd /Luca/app; ./../gradlew publishProductionBundle $GENERAL_PARAMS $KEYSTORE_PARAMS"
                        docker run --rm -u $(id -u):$(id -g) -v `pwd`:/Luca -v $SERVICE_ACCOUNT_FILE:/Luca/app/service-account.json -v $KEYSTORE_FILE:/Luca/app/$LOCAL_KEYSTORE_FILE ${CONTAINER} bash -c "$CMD"
                    '''
                }
            }
        }
        stage('Archive') {
            steps {
                sh "./Luca/scripts/rename_output_files"
                archiveArtifacts artifacts: 'Luca/app/build/outputs/apk/**/*.apk, Luca/app/build/outputs/bundle/**/*.aab, Luca/app/build/reports/dependency-check-report.html', excludes: 'Luca/app/build/outputs/apk/**/*-androidTest.apk', fingerprint: true
            }
        }
    }

    post {
        always {
            junit testResults: 'Luca/app/build/test-results/**/*.xml', allowEmptyResults: !params.RunTests
            build job: "Operations/Docker-Cleanup", wait: false
            cleanWs()
        }
    }
}